import { Geist, Geist_Mono,Fredoka } from "next/font/google";
import "./globals.css";``
import { AppProvider } from "@/context/DashBoardContext";
import ParentComp from "@/components/ParentComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "icon.svg" }],
};
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
   display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fredoka.className} antialiased
        
       
        `}
      >
        <AppProvider>
          <ParentComp>{children}</ParentComp>
        </AppProvider>
      </body>
    </html>
  );
}
