import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import { AppProvider } from "@/context/DashBoardContext";
import ParentComp from "@/components/ParentComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "icon.svg" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
       
        `}
      >
        <AppProvider>
          <ParentComp/>
        </AppProvider>
      </body>
    </html>
  );
}
